version: '3'
services:
  # PostgreSQL database container
  db:
    image: postgres:latest
    container_name: DatabaseContainer
    environment:
      POSTGRES_DB: reminders_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"  # Map the PostgreSQL container port to the host
    volumes:
      - db_data:/var/lib/postgresql/data  # Use the named volume for PostgreSQL data

  # Python application container
  createapp:
#    build:
#      context: ./CreateContainer  # Specify the path to the Dockerfile and build context
    image: create_reminders_app
    container_name: create_reminders_app
    depends_on:
      - db
    environment:
      DB_HOST: db  # This is the hostname of the PostgreSQL container within the Docker network
    command: python -i app.py  # Add the -i option to run Python in interactive mode
    stdin_open: true
    tty: true

#  getapp:
#    build:
#      context: ./GetContainer  # Specify the path to the Dockerfile and build context
#    container_name: get_reminders_app
#    depends_on:
#      - db
#    environment:
#      DB_HOST: db  # This is the hostname of the PostgreSQL container within the Docker network
#    command: python -i app.py  # Add the -i option to run Python in interactive mode
#    stdin_open: true
#    tty: true

volumes:
  db_data:


  # docker build . -t virtual_assistant_application
  # docker-compose up -d
  # docker-compose exec createapp python3 -i app.py
  # docker-compose exec getapp python3 -i app.py
  # docker exec -it DatabaseContainer reminders_db
  # psql -U singh123 -d tasks_db
  # select * from reminders;